favicon: null
name: Rough Roads
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.3978495
  brandStrength: 0
  lightness: 0.7759857
  brandColors:
    - '#0d0804'
    - '#ffffff'
    - '#593c23'
    - '#4d5e67'
    - '#c2b39e'
  rhythmicContrast: 0.6397849
typography_spectrum: 0
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.8942652
analytics:
  twitter: null
  google: null
  facebook: null
