layout_spectrum: 0.8297491
typography_spectrum: 0
color:
  saturation: 0.3978495
  lightness: 0.6559139
  brandStrength: 0.8518344
  rhythmicContrast: 0.6397849
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Rough Roads
